// <auto-generated />
using System;
using HospitalManagementData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HospitalManagementData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalManagementDomain.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RegisterationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppUser");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DoctorId1")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientId1")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId1");

                    b.HasIndex("PatientId1");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartmentInitials")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7da11ee0-2519-493f-816a-ba6f46aacb74"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(5025),
                            DepartmentInitials = "OTP",
                            DepartmentNumber = "OTP-1122334455",
                            Description = "This section of the hospital caters for patients that require medical attention but are notrequired to be admitted are treated",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(5035),
                            Name = "Outpatient Department"
                        },
                        new
                        {
                            Id = new Guid("7cd042ca-c443-4067-91c1-6d1df0fad8d5"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6401),
                            DepartmentInitials = "INP",
                            DepartmentNumber = "INP-1122334466",
                            Description = "This section of the hospital caters for patients that are required to be admitted for at least one night",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6403),
                            Name = "Inpatient Department"
                        },
                        new
                        {
                            Id = new Guid("368faff2-f91f-4de3-a9b9-ac6e659ced57"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6414),
                            DepartmentInitials = "PHY",
                            DepartmentNumber = "PHY-1122334477",
                            Description = "This section of the hospital contains all the doctors in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6415),
                            Name = "Physicians Department"
                        },
                        new
                        {
                            Id = new Guid("a0a2e6c6-3fee-46dc-a87e-dcb215029e93"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6418),
                            DepartmentInitials = "NUR",
                            DepartmentNumber = "NUR-1122334488",
                            Description = "This section of the hospital contains all the nurses in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6419),
                            Name = "Nursing Department"
                        },
                        new
                        {
                            Id = new Guid("12757ffa-ab81-4a23-b3a1-4f3fc169ec53"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6421),
                            DepartmentInitials = "PHM",
                            DepartmentNumber = "PHM-1122334499",
                            Description = "This section of the hospital contains all the pharmacists in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6422),
                            Name = "Pharmarcy Department"
                        },
                        new
                        {
                            Id = new Guid("501c0200-3c6d-48c7-8b6e-964a87f0c290"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6424),
                            DepartmentInitials = "MLA",
                            DepartmentNumber = "MLA-1122335511",
                            Description = "This section of the hospital contains all the laboratory scientists and radiologists in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6425),
                            Name = "Medical Laboratory Department"
                        },
                        new
                        {
                            Id = new Guid("295d3a0c-992c-4dfb-bcc2-e26fb6f9b4b8"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6427),
                            DepartmentInitials = "ACC",
                            DepartmentNumber = "ACC-1122335522",
                            Description = "This section of the hospital contains all the accountants in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6427),
                            Name = "Accounts Department"
                        },
                        new
                        {
                            Id = new Guid("91c4ebd1-33ae-4ef2-aeee-1d12e01d3dfb"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6429),
                            DepartmentInitials = "RCD",
                            DepartmentNumber = "RCD-1122335533",
                            Description = "This section of the hospital is tasked with managing all the records in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6430),
                            Name = "Records Department"
                        },
                        new
                        {
                            Id = new Guid("55ccc95d-caac-44fe-b3ee-8830184ee9b5"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6432),
                            DepartmentInitials = "JNT",
                            DepartmentNumber = "JNT-1122335544",
                            Description = "This section of the hospital contains all the maintenance and cleaning staff in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6433),
                            Name = "Janitorial Department"
                        },
                        new
                        {
                            Id = new Guid("2b212064-c708-44fd-a49a-6d138cdded37"),
                            CreatedAt = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6435),
                            DepartmentInitials = "SEC",
                            DepartmentNumber = "SEC-1122335566",
                            Description = "This section of the hospital contains all the security officers in the hospital",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 598, DateTimeKind.Utc).AddTicks(6435),
                            Name = "Security Department"
                        });
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.DrugOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("StaffId")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("StaffId");

                    b.ToTable("DrugOrders");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "27fb1887-cf6f-45d8-83d1-c501d6054fd3",
                            ConcurrencyStamp = "ac5d2cbe-2791-439c-ba31-a3b0d8010f40",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "5af1f3a1-f7f9-4ad0-b757-cda796199def",
                            ConcurrencyStamp = "fe68d865-34be-47e0-b07b-9a052073caca",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "67228962-a44c-49a6-b89b-395dd92cf75a",
                            ConcurrencyStamp = "ca504b07-00ae-40cd-9a13-c3c65c401b48",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "a1ff4611-dc37-4a8e-af8e-73e764fc8676",
                            ConcurrencyStamp = "b254276b-10be-4bcb-beec-93a75d18f27b",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "300ddf19-95e6-4744-83e6-2aa5e1d444c0",
                            RoleId = "67228962-a44c-49a6-b89b-395dd92cf75a"
                        },
                        new
                        {
                            UserId = "300ddf19-95e6-4744-83e6-2aa5e1d444c0",
                            RoleId = "27fb1887-cf6f-45d8-83d1-c501d6054fd3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Patient", b =>
                {
                    b.HasBaseType("HospitalManagementDomain.Models.AppUser");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Genotype")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Staff", b =>
                {
                    b.HasBaseType("HospitalManagementDomain.Models.AppUser");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentNumber")
                        .HasColumnType("text");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue("Staff");

                    b.HasData(
                        new
                        {
                            Id = "300ddf19-95e6-4744-83e6-2aa5e1d444c0",
                            AccessFailedCount = 0,
                            Address = "Hospital Management Location",
                            ConcurrencyStamp = "4598c2f5-24f2-4842-88f1-0c48e0aeb7d5",
                            Email = "admin@hospitalManagement.com",
                            EmailConfirmed = true,
                            FirstName = "Hospital",
                            IdentificationNumber = "ST-1001123355",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            MiddleName = "Default",
                            ModifiedOn = new DateTime(2022, 6, 22, 12, 33, 21, 600, DateTimeKind.Utc).AddTicks(1238),
                            NormalizedEmail = "ADMIN@HOSPITALMANAGEMENT.COM",
                            NormalizedUserName = "ADMIN@HOSPITALMANAGEMENT.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEK0Fn1QYqX+UyiCEbFRZOUjXIjeBrTV4oRNovC3M/wxH/SoTZvLfft7Vjh4QbcDkJg==",
                            PhoneNumber = "+2348064879196",
                            PhoneNumberConfirmed = true,
                            RegisterationDate = new DateTime(2022, 6, 22, 12, 33, 21, 600, DateTimeKind.Utc).AddTicks(1229),
                            SecurityStamp = "dbba1baa-1055-433d-b4ce-c505700fd5a9",
                            Sex = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin@hospitalManagement.com",
                            DepartmentId = new Guid("2b212064-c708-44fd-a49a-6d138cdded37"),
                            DepartmentNumber = "SEC-1122335566"
                        });
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Doctor", b =>
                {
                    b.HasBaseType("HospitalManagementDomain.Models.Staff");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Appointment", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId1");

                    b.HasOne("HospitalManagementDomain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId1");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.DrugOrder", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementDomain.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId");

                    b.Navigation("Drug");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementDomain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagementDomain.Models.Staff", b =>
                {
                    b.HasOne("HospitalManagementDomain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
